modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/iTitus/nbtviewer/issues"
license = "MIT"

[[mods]]
modId = "nbtviewer"
version = "${file.jarVersion}"
displayName = "NBT Viewer"
displayURL = "https://github.com/iTitus/nbtviewer"
updateJSONURL = "https://raw.githubusercontent.com/iTitus/nbtviewer/main/update.json"
authors = "iTitus"
description = '''
View NBT of Items, Entities and Block Entities
'''

[[dependencies.nbtviewer]]
modId = "forge"
mandatory = true
versionRange = "[34.0.17,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nbtviewer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3,)"
ordering = "NONE"
side = "BOTH"
